### ISSUE TITLE
Prototyping virtual kubelete-based k8s cluster

### ISSUE THREAD

**Issue by gurjyan** [JeffersonLab/jiriaf-0.1#2]
Develop a prototype of the virtual kubelet as a component of the Jiriaf Resource Manager (JRM) that operates within the user space and integrates into the Jiriaf Kubernetes (k8s) cluster.

**Comment by tsaie79** [comment]
This is done by deploying the virtual kubelet(VK) in userspace in compute sites, and VKs can form a K8s cluster, which can be seen by K8s control plane.

Our vk-cmd is a shell command provider based on the [mock provider](https://github.com/virtual-kubelet/virtual-kubelet).
